import { Product } from './types';

export const PRODUCTS: Product[] = [
  // 10 Bedspread & Pillow Sets
  {
    id: 'acr-set-01',
    slug: 'royal-damask-bedspread-set-01',
    name: 'Royal Damask Bedspread & Pillow Set — Edition 01',
    category: 'bedspread-sets',
    categoryLabel: 'Bedspread & Pillow Sets',
    price: 299,
    compareAtPrice: 389,
    shortDescription: 'Deep navy ground adorned with regal acanthus scrollwork and a botanical medallion.',
    description: 'The crowning centerpiece of ACR Cottons. Woven in Erode using pure long-staple combed cotton, this ensemble features an opulent baroque medallion framed by architectural flourishes. Naturally breathable and engineered for an unyielding boutique hotel hand feel.',
    highlightedMaterial: '100% Combed Erode Cotton • 400 TC Jacquard Damask',
    weave: 'Architectural Jacquard Damask',
    threadCount: 400,
    setContents: '1× Luxury Bedspread + 2× Matching Pillow Shams',
    image: '/assets/designs/design1.webp',
    thumbnail: '/assets/designs/design1_thumb.webp',
    images: ['/assets/designs/design1.webp'],
    designNumber: 1,
    sizes: [
      { id: 'queen', name: 'Queen Set', dimensions: '90″ × 100″ + 2 Shams (20″ × 26″)', inStock: true },
      { id: 'king', name: 'King Set', dimensions: '108″ × 108″ + 2 King Shams (20″ × 36″)', inStock: true },
    ],
    rating: 4.9,
    reviewCount: 48,
    inStock: true,
    badge: 'Atelier Signature',
    careInstructions: [
      'Machine wash gentle cycle with cold water',
      'Use mild, enzyme-free detergent',
      'Tumble dry low or line dry in shade',
      'Warm iron on reverse if desired',
    ],
  },
  {
    id: 'acr-set-02',
    slug: 'serene-indigo-vine-bedspread-set-02',
    name: 'Serene Indigo Vine Bedspread & Pillow Set — Edition 02',
    category: 'bedspread-sets',
    categoryLabel: 'Bedspread & Pillow Sets',
    price: 189,
    compareAtPrice: 249,
    shortDescription: 'Gentle textured denim-blue ground with a slender vertical botanical vine.',
    description: 'Crafted for tranquil bedroom sanctuaries. The gentle textured grid mimics traditional slub weave, balanced by cascading leafy bellflowers in ivory and midnight blue. Includes matching envelope-closure pillowcases.',
    highlightedMaterial: '100% Combed Cotton • Slub Texture Weave',
    weave: 'Slub Textured Weave',
    threadCount: 350,
    setContents: '1× Luxury Bedspread + 2× Matching Pillow Shams',
    image: '/assets/designs/design2.webp',
    thumbnail: '/assets/designs/design2_thumb.webp',
    images: ['/assets/designs/design2.webp'],
    designNumber: 2,
    sizes: [
      { id: 'queen', name: 'Queen Set', dimensions: '90″ × 100″ + 2 Shams (20″ × 26″)', inStock: true },
      { id: 'king', name: 'King Set', dimensions: '108″ × 108″ + 2 King Shams (20″ × 36″)', inStock: true },
    ],
    rating: 4.8,
    reviewCount: 34,
    inStock: true,
    badge: 'Minimalist Favorite',
    careInstructions: [
      'Machine wash cold, gentle cycle',
      'Wash with similar light colors',
      'Tumble dry low',
      'No chlorine bleach',
    ],
  },
  {
    id: 'acr-set-03',
    slug: 'imperial-lotus-jacquard-set-03',
    name: 'Imperial Lotus Jacquard Bedspread & Pillow Set — Edition 03',
    category: 'bedspread-sets',
    categoryLabel: 'Bedspread & Pillow Sets',
    price: 249,
    compareAtPrice: 319,
    shortDescription: 'Warm heritage floral damask with symmetrical botanical urns and borders.',
    description: 'An homage to South Indian palatial residences. Features classical lotus urn motifs woven in tactile raised relief, ensuring the fabric retains its crisp elegance wash after wash.',
    highlightedMaterial: '100% Long-Staple Cotton • Raised Relief Jacquard',
    weave: 'Raised Relief Jacquard',
    threadCount: 420,
    setContents: '1× Luxury Bedspread + 2× Matching Pillow Shams',
    image: '/assets/designs/design3.webp',
    thumbnail: '/assets/designs/design3_thumb.webp',
    images: ['/assets/designs/design3.webp'],
    designNumber: 3,
    sizes: [
      { id: 'queen', name: 'Queen Set', dimensions: '90″ × 100″ + 2 Shams (20″ × 26″)', inStock: true },
      { id: 'king', name: 'King Set', dimensions: '108″ × 108″ + 2 King Shams (20″ × 36″)', inStock: true },
    ],
    rating: 4.9,
    reviewCount: 29,
    inStock: true,
    badge: 'Heritage Loom',
    careInstructions: ['Dry clean or machine wash cold gentle', 'Line dry recommended'],
  },
  {
    id: 'acr-set-04',
    slug: 'heritage-paisley-bedspread-set-04',
    name: 'Heritage Paisley Bedspread & Pillow Set — Edition 04',
    category: 'bedspread-sets',
    categoryLabel: 'Bedspread & Pillow Sets',
    price: 219,
    compareAtPrice: 289,
    shortDescription: 'Intricate paisley tear motifs interwoven with geometric lattice accents.',
    description: 'Textile history brought into contemporary luxury. Combed yarns woven tightly on powerlooms in Surampatti Valasu, delivering a silky-smooth surface with exceptional drape.',
    highlightedMaterial: '100% Combed Cotton • Micro-Sateen Luster',
    weave: 'Micro-Sateen Weave',
    threadCount: 380,
    setContents: '1× Luxury Bedspread + 2× Matching Pillow Shams',
    image: '/assets/designs/design4.webp',
    thumbnail: '/assets/designs/design4_thumb.webp',
    images: ['/assets/designs/design4.webp'],
    designNumber: 4,
    sizes: [
      { id: 'queen', name: 'Queen Set', dimensions: '90″ × 100″ + 2 Shams (20″ × 26″)', inStock: true },
      { id: 'king', name: 'King Set', dimensions: '108″ × 108″ + 2 King Shams (20″ × 36″)', inStock: true },
    ],
    rating: 4.7,
    reviewCount: 21,
    inStock: true,
    careInstructions: ['Gentle cycle machine wash', 'Tumble dry low'],
  },
  {
    id: 'acr-set-05',
    slug: 'marigold-sovereign-bedspread-set-05',
    name: 'Marigold Sovereign Bedspread & Pillow Set — Edition 05',
    category: 'bedspread-sets',
    categoryLabel: 'Bedspread & Pillow Sets',
    price: 279,
    compareAtPrice: 349,
    shortDescription: 'Golden ochre and sand botanical arabesques for warm, regal bedrooms.',
    description: 'Infused with the natural warmth of South Indian turmeric and marigold tones. The high thread-count cotton delivers cloud-soft sleep without trapping humidity.',
    highlightedMaterial: '100% Pure Combed Cotton • Double-Pick Weave',
    weave: 'Double-Pick Jacquard',
    threadCount: 450,
    setContents: '1× Luxury Bedspread + 2× Matching Pillow Shams',
    image: '/assets/designs/design5.webp',
    thumbnail: '/assets/designs/design5_thumb.webp',
    images: ['/assets/designs/design5.webp'],
    designNumber: 5,
    sizes: [
      { id: 'queen', name: 'Queen Set', dimensions: '90″ × 100″ + 2 Shams (20″ × 26″)', inStock: true },
      { id: 'king', name: 'King Set', dimensions: '108″ × 108″ + 2 King Shams (20″ × 36″)', inStock: true },
    ],
    rating: 4.9,
    reviewCount: 38,
    inStock: true,
    badge: 'Artisan Pick',
    careInstructions: ['Wash inside out in cold water', 'Warm iron on reverse'],
  },
  {
    id: 'acr-set-06',
    slug: 'botanical-whisper-bedspread-set-06',
    name: 'Botanical Whisper Bedspread & Pillow Set — Edition 06',
    category: 'bedspread-sets',
    categoryLabel: 'Bedspread & Pillow Sets',
    price: 199,
    compareAtPrice: 259,
    shortDescription: 'Subtle ivory flora traced upon a whisper-soft mist gray foundation.',
    description: 'Understated luxury designed for minimal, clutter-free bedrooms. Clean lines, lightweight breathability, and matching pillowcases that soften progressively with every wash.',
    highlightedMaterial: '100% Organic Erode Cotton • Percale Weave',
    weave: 'Crisp Percale Weave',
    threadCount: 320,
    setContents: '1× Luxury Bedspread + 2× Matching Pillow Shams',
    image: '/assets/designs/design6.webp',
    thumbnail: '/assets/designs/design6_thumb.webp',
    images: ['/assets/designs/design6.webp'],
    designNumber: 6,
    sizes: [
      { id: 'queen', name: 'Queen Set', dimensions: '90″ × 100″ + 2 Shams (20″ × 26″)', inStock: true },
      { id: 'king', name: 'King Set', dimensions: '108″ × 108″ + 2 King Shams (20″ × 36″)', inStock: true },
    ],
    rating: 4.8,
    reviewCount: 19,
    inStock: true,
    careInstructions: ['Machine wash 30°C', 'Air dry in gentle breeze'],
  },
  {
    id: 'acr-set-07',
    slug: 'midnight-baroque-bedspread-set-07',
    name: 'Midnight Baroque Bedspread & Pillow Set — Edition 07',
    category: 'bedspread-sets',
    categoryLabel: 'Bedspread & Pillow Sets',
    price: 289,
    compareAtPrice: 369,
    shortDescription: 'Dramatic midnight indigo with contrast ivory rococo frame borders.',
    description: 'An architectural statement piece. The contrasting border creates sharp perimeter geometry around king and queen mattresses, providing an instantly tailored bedroom appearance.',
    highlightedMaterial: '100% Combed Cotton • High-Definition Rotary Weave',
    weave: 'Rotary Jacquard',
    threadCount: 400,
    setContents: '1× Luxury Bedspread + 2× Matching Pillow Shams',
    image: '/assets/designs/design7.webp',
    thumbnail: '/assets/designs/design7_thumb.webp',
    images: ['/assets/designs/design7.webp'],
    designNumber: 7,
    sizes: [
      { id: 'queen', name: 'Queen Set', dimensions: '90″ × 100″ + 2 Shams (20″ × 26″)', inStock: true },
      { id: 'king', name: 'King Set', dimensions: '108″ × 108″ + 2 King Shams (20″ × 36″)', inStock: true },
    ],
    rating: 5.0,
    reviewCount: 42,
    inStock: true,
    badge: 'Popular Choice',
    careInstructions: ['Cold wash gentle', 'Do not tumble dry on high heat'],
  },
  {
    id: 'acr-set-08',
    slug: 'erode-artisan-floral-set-08',
    name: 'Erode Artisan Floral Bedspread & Pillow Set — Edition 08',
    category: 'bedspread-sets',
    categoryLabel: 'Bedspread & Pillow Sets',
    price: 229,
    compareAtPrice: 299,
    shortDescription: 'Delicate floral sprays honoring traditional Cauvery basin dye motifs.',
    description: 'Every flower in this tapestry is derived from historical block-printing patterns revived in ACR Cottons modern automated looms. Rich, soft, and completely lint-free.',
    highlightedMaterial: '100% Combed Long-Staple Cotton',
    weave: 'Classic Sateen Weave',
    threadCount: 360,
    setContents: '1× Luxury Bedspread + 2× Matching Pillow Shams',
    image: '/assets/designs/design8.webp',
    thumbnail: '/assets/designs/design8_thumb.webp',
    images: ['/assets/designs/design8.webp'],
    designNumber: 8,
    sizes: [
      { id: 'queen', name: 'Queen Set', dimensions: '90″ × 100″ + 2 Shams (20″ × 26″)', inStock: true },
      { id: 'king', name: 'King Set', dimensions: '108″ × 108″ + 2 King Shams (20″ × 36″)', inStock: true },
    ],
    rating: 4.8,
    reviewCount: 26,
    inStock: true,
    careInstructions: ['Gentle cycle cold', 'Tumble dry low'],
  },
  {
    id: 'acr-set-09',
    slug: 'grand-palais-damask-set-09',
    name: 'Grand Palais Damask Bedspread & Pillow Set — Edition 09',
    category: 'bedspread-sets',
    categoryLabel: 'Bedspread & Pillow Sets',
    price: 269,
    compareAtPrice: 339,
    shortDescription: 'Intricate European-inspired scroll medallions crafted on South Indian looms.',
    description: 'A cross-continental fusion of Versailles damask grandeur and South Indian weaving mastery. The substantial fabric weight holds its position on the bed without slipping or bunching.',
    highlightedMaterial: '100% Combed Cotton • Heavyweight 380 GSM',
    weave: 'Heavy Jacquard Weave',
    threadCount: 420,
    setContents: '1× Luxury Bedspread + 2× Matching Pillow Shams',
    image: '/assets/designs/design9.webp',
    thumbnail: '/assets/designs/design9_thumb.webp',
    images: ['/assets/designs/design9.webp'],
    designNumber: 9,
    sizes: [
      { id: 'queen', name: 'Queen Set', dimensions: '90″ × 100″ + 2 Shams (20″ × 26″)', inStock: true },
      { id: 'king', name: 'King Set', dimensions: '108″ × 108″ + 2 King Shams (20″ × 36″)', inStock: true },
    ],
    rating: 4.9,
    reviewCount: 31,
    inStock: true,
    careInstructions: ['Dry clean or delicate cold wash'],
  },
  {
    id: 'acr-set-10',
    slug: 'classical-acanthus-bedspread-set-10',
    name: 'Classical Acanthus Bedspread & Pillow Set — Edition 10',
    category: 'bedspread-sets',
    categoryLabel: 'Bedspread & Pillow Sets',
    price: 239,
    compareAtPrice: 309,
    shortDescription: 'Graceful flowing acanthus leaves framing a center floral arrangement.',
    description: 'Balanced symmetry meets tactile cotton softness. Ideal for both modern neutral rooms and traditional teak-furnished suites.',
    highlightedMaterial: '100% Combed Cotton • Silken Finished Fibers',
    weave: 'Damask Figured Weave',
    threadCount: 390,
    setContents: '1× Luxury Bedspread + 2× Matching Pillow Shams',
    image: '/assets/designs/design10.webp',
    thumbnail: '/assets/designs/design10_thumb.webp',
    images: ['/assets/designs/design10.webp'],
    designNumber: 10,
    sizes: [
      { id: 'queen', name: 'Queen Set', dimensions: '90″ × 100″ + 2 Shams (20″ × 26″)', inStock: true },
      { id: 'king', name: 'King Set', dimensions: '108″ × 108″ + 2 King Shams (20″ × 36″)', inStock: true },
    ],
    rating: 4.9,
    reviewCount: 28,
    inStock: true,
    careInstructions: ['Machine wash cold, low spin', 'Line dry'],
  },

  // Curated Boxes
  {
    id: 'box-royal-neutral',
    slug: 'royal-neutral-bed-set-box',
    name: 'The Royal Neutral Bed Set Box',
    category: 'curated-boxes',
    categoryLabel: 'Curated Subscription & Gift Boxes',
    price: 349,
    compareAtPrice: 449,
    shortDescription: 'Complete curated suite: 1 Bedspread, 2 Pillow Shams, 1 Velvet Cushion & Linen Pouch.',
    description: 'Hand-selected by founder A.C. Raj Kumar. A total bedroom transformation presented in our signature rigid gold-embossed keepsake box. Features a calming palette of warm ecru, sand, and brushed gold.',
    highlightedMaterial: 'Curated Luxury Bedding Box • 100% Erode Cotton + Velvet',
    weave: 'Multi-Textile Curated Suite',
    threadCount: 420,
    setContents: '1× Bedspread + 2× Pillow Shams + 1× Velvet Lumbar Cushion + Keepsake Box',
    image: '/assets/designs/design1.webp',
    thumbnail: '/assets/designs/design1_thumb.webp',
    images: ['/assets/designs/design1.webp', '/assets/designs/design5.webp'],
    sizes: [
      { id: 'box-queen', name: 'Queen Box Suite', dimensions: 'Complete Queen Bed Suite', inStock: true },
      { id: 'box-king', name: 'King Box Suite', dimensions: 'Complete King Bed Suite', inStock: true },
    ],
    rating: 5.0,
    reviewCount: 52,
    inStock: true,
    badge: 'Curated Gift Box',
    careInstructions: ['Care guides included for each textile component inside the box'],
  },
  {
    id: 'box-bold-vibrant',
    slug: 'bold-vibrant-sheet-sets-box',
    name: 'Bold & Vibrant Sheet Sets Box',
    category: 'curated-boxes',
    categoryLabel: 'Curated Subscription & Gift Boxes',
    price: 389,
    compareAtPrice: 499,
    shortDescription: 'Celebratory festival edition: 1 Jacquard Bedspread, 2 Shams, 2 Accent Cushions.',
    description: 'An energizing celebration of traditional South Indian artisan prints. Packed with rich royal blues, deep golds, and terracotta accents, this box includes a full bedspread set accompanied by two plush accent cushions.',
    highlightedMaterial: 'Heavyweight Jacquard & Embroidered Linen Suite',
    weave: 'Celebratory Artisan Weave',
    threadCount: 450,
    setContents: '1× Jacquard Bedspread + 2× Shams + 2× Decorative Cushions + Box',
    image: '/assets/designs/design7.webp',
    thumbnail: '/assets/designs/design7_thumb.webp',
    images: ['/assets/designs/design7.webp', '/assets/designs/design3.webp'],
    sizes: [
      { id: 'box-queen', name: 'Queen Box Suite', dimensions: 'Complete Queen Bed Suite', inStock: true },
      { id: 'box-king', name: 'King Box Suite', dimensions: 'Complete King Bed Suite', inStock: true },
    ],
    rating: 4.9,
    reviewCount: 39,
    inStock: true,
    badge: 'Festive Limited Edition',
    careInstructions: ['Dry clean or delicate cycle cold'],
  },

  // Cushions & Shams (from Excel)
  {
    id: 'cushion-velvet-lumbar',
    slug: 'velvet-lumbar-cushion',
    name: 'Velvet Lumbar Cushion',
    category: 'cushions',
    categoryLabel: 'Accent Cushions',
    price: 89,
    compareAtPrice: 119,
    shortDescription: 'Plush velvet lumbar accent with piping and discreet brass zip.',
    description: 'The definitive boutique hotel accent. Features a dense, directional pile that catches the light with subtle warmth. Stuffed with hypoallergenic micro-cluster fiber for enduring loft.',
    highlightedMaterial: 'Dense Plush Velvet • Hypoallergenic Fill',
    weave: 'Cut-Pile Velvet Weave',
    threadCount: 300,
    setContents: '1× Luxury Lumbar Cushion with Insert',
    image: '/assets/designs/design5.webp',
    thumbnail: '/assets/designs/design5_thumb.webp',
    images: ['/assets/designs/design5.webp'],
    sizes: [
      { id: 'std-lumbar', name: 'Standard Lumbar', dimensions: '14″ × 24″ (35cm × 60cm)', inStock: true },
    ],
    rating: 4.8,
    reviewCount: 17,
    inStock: true,
    careInstructions: ['Spot clean only with soft damp cloth', 'Do not machine wash insert'],
  },
  {
    id: 'cushion-intricate-jacquard',
    slug: 'intricate-jacquard-pillow',
    name: 'Intricate Jacquard Pillow',
    category: 'cushions',
    categoryLabel: 'Accent Cushions',
    price: 99,
    compareAtPrice: 129,
    shortDescription: 'Structured square pillow highlighting raised tactile Jacquard weaving.',
    description: 'Elevates any sofa or armchair. Woven with double-twisted cotton threads to ensure structural rigidity and timeless visual texture.',
    highlightedMaterial: '100% Combed Cotton Jacquard Weave',
    weave: 'Structured Relief Jacquard',
    threadCount: 400,
    setContents: '1× Square Cushion with Plush Insert',
    image: '/assets/designs/design1.webp',
    thumbnail: '/assets/designs/design1_thumb.webp',
    images: ['/assets/designs/design1.webp'],
    sizes: [
      { id: 'sq-18', name: 'Square 18″', dimensions: '18″ × 18″ (45cm × 45cm)', inStock: true },
      { id: 'sq-20', name: 'Square 20″', dimensions: '20″ × 20″ (50cm × 50cm)', inStock: true },
    ],
    rating: 4.9,
    reviewCount: 23,
    inStock: true,
    careInstructions: ['Remove cover and hand wash cold', 'Lay flat to dry'],
  },
  {
    id: 'cushion-embroidered-accent',
    slug: 'embroidered-accent-cushion',
    name: 'Embroidered Accent Cushion',
    category: 'cushions',
    categoryLabel: 'Accent Cushions',
    price: 75,
    compareAtPrice: 95,
    shortDescription: 'Soft blush linen base with metallic antique branch embroidery.',
    description: 'Delicate metallic gold branch embroidery stitched onto natural washed linen. Brings quiet luster to neutral bedding.',
    highlightedMaterial: 'Natural Linen & Cotton Blend • Metallic Thread Embroidery',
    weave: 'Linen Plain Weave + Embroidery',
    threadCount: 300,
    setContents: '1× Embroidered Cushion with Insert',
    image: '/assets/designs/design2.webp',
    thumbnail: '/assets/designs/design2_thumb.webp',
    images: ['/assets/designs/design2.webp'],
    sizes: [
      { id: 'sq-16', name: 'Square 16″', dimensions: '16″ × 16″ (40cm × 40cm)', inStock: true },
    ],
    rating: 4.7,
    reviewCount: 14,
    inStock: true,
    careInstructions: ['Dry clean recommended', 'Cool iron on reverse'],
  },
  {
    id: 'sham-satin-european',
    slug: 'satin-european-sham',
    name: 'Satin European Sham',
    category: 'pillowcases',
    categoryLabel: 'Pillowcases & Shams',
    price: 79,
    compareAtPrice: 99,
    shortDescription: 'Square European-size sham with silken sateen border flange.',
    description: 'Designed as backdrop pillows for master suites. The lustrous sateen weave feels frictionless against hair and skin, resisting wrinkles.',
    highlightedMaterial: '100% Combed Cotton Sateen • 450 TC',
    weave: 'Lustrous Sateen Weave',
    threadCount: 450,
    setContents: '1× Euro Pillow Sham (Insert not included)',
    image: '/assets/designs/design4.webp',
    thumbnail: '/assets/designs/design4_thumb.webp',
    images: ['/assets/designs/design4.webp'],
    sizes: [
      { id: 'euro', name: 'Euro Sham', dimensions: '26″ × 26″ (66cm × 66cm)', inStock: true },
    ],
    rating: 4.8,
    reviewCount: 19,
    inStock: true,
    careInstructions: ['Machine wash gentle cold', 'Tumble dry low'],
  },
  {
    id: 'sham-textured-queen',
    slug: 'textured-queen-pillowcase',
    name: 'Textured Queen Pillowcase',
    category: 'pillowcases',
    categoryLabel: 'Pillowcases & Shams',
    price: 55,
    compareAtPrice: 75,
    shortDescription: 'Tactile woven texture with an extra-deep internal envelope flap.',
    description: 'Ensures pillows stay securely tucked inside. The fine micro-texture offers gentle tactile comfort without causing sleep creases.',
    highlightedMaterial: '100% Combed Erode Cotton',
    weave: 'Micro-Textured Weave',
    threadCount: 350,
    setContents: '1× Queen Pillowcase',
    image: '/assets/designs/design8.webp',
    thumbnail: '/assets/designs/design8_thumb.webp',
    images: ['/assets/designs/design8.webp'],
    sizes: [
      { id: 'queen-case', name: 'Queen Size', dimensions: '20″ × 30″ (50cm × 76cm)', inStock: true },
    ],
    rating: 4.6,
    reviewCount: 12,
    inStock: true,
    careInstructions: ['Machine wash warm', 'Tumble dry normal'],
  },
  {
    id: 'sham-embellished-standard',
    slug: 'embellished-standard-pillowcase',
    name: 'Embellished Standard Pillowcase',
    category: 'pillowcases',
    categoryLabel: 'Pillowcases & Shams',
    price: 65,
    compareAtPrice: 85,
    shortDescription: 'Classic standard pillowcase finished with an artisanal hemstitch flange.',
    description: 'Timeless tailored simplicity. The delicate hemstitch border speaks of vintage tailoring traditions upheld by Erode seamstresses.',
    highlightedMaterial: '100% Combed Cotton • Hemstitch Flange',
    weave: 'Percale with Hemstitch Detailing',
    threadCount: 380,
    setContents: '1× Standard Pillowcase',
    image: '/assets/designs/design6.webp',
    thumbnail: '/assets/designs/design6_thumb.webp',
    images: ['/assets/designs/design6.webp'],
    sizes: [
      { id: 'std-case', name: 'Standard Size', dimensions: '20″ × 26″ (50cm × 66cm)', inStock: true },
    ],
    rating: 4.7,
    reviewCount: 16,
    inStock: true,
    careInstructions: ['Machine wash cold', 'Warm iron while slightly damp'],
  },
];
