import { Review } from './types';

export const INITIAL_REVIEWS: Review[] = [
  // Edition 01 — Royal Jacquard Relief
  {
    id: 'rev-01-1',
    productId: 'acr-set-01',
    userName: 'Kavitha Ramaswamy',
    userCity: 'Chennai, TN',
    rating: 5,
    title: 'Pure boutique hotel luxury for our master suite',
    comment: 'The navy and gold damask pattern is even more stunning in person than on screen. The fabric has an authentic weight to it that stays perfectly in place on our king bed. Woven craftsmanship at its absolute finest.',
    verifiedPurchase: true,
    createdAt: '12 September 2026',
  },
  {
    id: 'rev-01-2',
    productId: 'acr-set-01',
    userName: 'Arjun Menon',
    userCity: 'Bangalore, KA',
    rating: 5,
    title: 'The combed cotton breathability is remarkable',
    comment: 'Unlike polyester blends that get stuffy, this combed cotton breathes wonderfully through warm nights. The two matching pillow covers complete the aesthetic effortlessly.',
    verifiedPurchase: true,
    createdAt: '04 September 2026',
  },
  {
    id: 'rev-01-3',
    productId: 'acr-set-01',
    userName: 'Sangeetha Natarajan',
    userCity: 'Coimbatore, TN',
    rating: 5,
    title: 'Proud of our Erode textile heritage',
    comment: 'Knowing this is woven right here in the Textile Valley of Erode makes it even more special. The hemstitch borders and jacquard relief are pristine. Will be ordering another set for the guest bedroom.',
    verifiedPurchase: true,
    createdAt: '28 August 2026',
  },

  // Edition 02 — Serene Indigo Vine
  {
    id: 'rev-02-1',
    productId: 'acr-set-02',
    userName: 'Deepak Varma',
    userCity: 'Kochi, KL',
    rating: 5,
    title: 'Tranquil indigo slub weave with pristine hand feel',
    comment: 'The soft denim blue and organic leafy vines create a very calm sanctuary in our room. The envelope-closure pillow covers are tailored to perfection.',
    verifiedPurchase: true,
    createdAt: '10 September 2026',
  },
  {
    id: 'rev-02-2',
    productId: 'acr-set-02',
    userName: 'Ananya Deshmukh',
    userCity: 'Mumbai, MH',
    rating: 5,
    title: 'Lightweight yet incredibly durable',
    comment: 'Machine washed twice already with mild detergent; no color bleeding and the combed cotton feels even softer now.',
    verifiedPurchase: true,
    createdAt: '01 September 2026',
  },
  {
    id: 'rev-02-3',
    productId: 'acr-set-02',
    userName: 'Suresh Krishnamurthy',
    userCity: 'Bengaluru, KA',
    rating: 5,
    title: 'Subtle slub weave texture with timeless botanical motifs',
    comment: 'The texture is earthy and grounding. Perfect weight for air-conditioned rooms without feeling overly bulky.',
    verifiedPurchase: true,
    createdAt: '22 August 2026',
  },

  // Edition 03 — Imperial Lotus Jacquard
  {
    id: 'rev-03-1',
    productId: 'acr-set-03',
    userName: 'Dr. Rajesh Sundaram',
    userCity: 'Erode, TN',
    rating: 5,
    title: 'True palatial aesthetic and regal symmetry',
    comment: 'The lotus urn motifs are woven with an authentic raised relief that gives the bedspread rich architectural depth. Worth every rupee.',
    verifiedPurchase: true,
    createdAt: '14 September 2026',
  },
  {
    id: 'rev-03-2',
    productId: 'acr-set-03',
    userName: 'Malini Venugopal',
    userCity: 'Madurai, TN',
    rating: 5,
    title: 'Pure combed long-staple cotton — stays cool all night',
    comment: 'The 420 thread count jacquard feels substantial and stays crisp on the bed. Delivery was swift with cash on delivery payment.',
    verifiedPurchase: true,
    createdAt: '06 September 2026',
  },
  {
    id: 'rev-03-3',
    productId: 'acr-set-03',
    userName: 'Gautam Nambiar',
    userCity: 'Trivandrum, KL',
    rating: 5,
    title: 'The matching pillow shams elevate the whole bedroom',
    comment: 'The tailored border on the shams frames our king pillows neatly. Remarkable artisanal standard directly from Erode powerlooms.',
    verifiedPurchase: true,
    createdAt: '25 August 2026',
  },
  {
    id: 'rev-03-4',
    productId: 'acr-set-03',
    userName: 'Preethi Selvam',
    userCity: 'Coimbatore, TN',
    rating: 5,
    title: 'Remarkable jacquard relief weave — five star rating',
    comment: 'The quality of the cotton and thickness of the bedspread is beyond what you find in commercial stores. It feels like bespoke heritage linen.',
    verifiedPurchase: true,
    createdAt: '18 August 2026',
  },

  // Edition 04 — Paisley Damask
  {
    id: 'rev-04-1',
    productId: 'acr-set-04',
    userName: 'Sunita Agarwal',
    userCity: 'Jaipur, RJ',
    rating: 5,
    title: 'Intricate paisley teardrops and silky micro-sateen drape',
    comment: 'The paisley detailing is so fine and tactile. The cotton has a natural, subtle luster that feels like an expensive hotel suite.',
    verifiedPurchase: true,
    createdAt: '08 September 2026',
  },
  {
    id: 'rev-04-2',
    productId: 'acr-set-04',
    userName: 'Rohit Singhania',
    userCity: 'Chandigarh, PB',
    rating: 5,
    title: 'Unbelievable micro-sateen finish that does not slip',
    comment: 'Unlike cheap synthetic satin, this pure sateen cotton has substantial grip while keeping that silken, smooth finish.',
    verifiedPurchase: true,
    createdAt: '02 September 2026',
  },
  {
    id: 'rev-04-3',
    productId: 'acr-set-04',
    userName: 'Neha Parikh',
    userCity: 'Ahmedabad, GJ',
    rating: 5,
    title: 'Pristine tailoring on both bedspread and pillow covers',
    comment: 'The stitching along the perimeter is reinforced and neat. Perfect fit for our king size bed.',
    verifiedPurchase: true,
    createdAt: '20 August 2026',
  },

  // Edition 05 — Royal Sapphire Jacquard
  {
    id: 'rev-05-1',
    productId: 'acr-set-05',
    userName: 'Karthik Balakrishnan',
    userCity: 'Hyderabad, TS',
    rating: 5,
    title: 'Double-pick jacquard weave with royal contrast',
    comment: 'The deep sapphire background paired with the sateen border looks opulent under warm bedside lamps. Zero pilling.',
    verifiedPurchase: true,
    createdAt: '11 September 2026',
  },
  {
    id: 'rev-05-2',
    productId: 'acr-set-05',
    userName: 'Srikant Raman',
    userCity: 'Chennai, TN',
    rating: 5,
    title: 'Rich deep sapphire dye with lustrous highlights',
    comment: 'The color intensity is stunning. Even after the first wash, there was no fading or bleeding. Authentic long-staple cotton.',
    verifiedPurchase: true,
    createdAt: '03 September 2026',
  },
  {
    id: 'rev-05-3',
    productId: 'acr-set-05',
    userName: 'Vandana Hegde',
    userCity: 'Mangalore, KA',
    rating: 5,
    title: 'Substantial 380 GSM weight keeps bed perfectly made',
    comment: 'You do not have to constantly adjust the sheets. It settles smoothly and gives the whole master bedroom a clean, tailored finish.',
    verifiedPurchase: true,
    createdAt: '27 August 2026',
  },

  // Edition 06 — Crisp Percale Medallion
  {
    id: 'rev-06-1',
    productId: 'acr-set-06',
    userName: 'Rhea Sengupta',
    userCity: 'Kolkata, WB',
    rating: 5,
    title: 'Crisp percale hand feel with timeless medallion',
    comment: 'Super fresh, matte, and crisp. Perfect for warmer climates. The medallion layout aligns centered on our queen mattress.',
    verifiedPurchase: true,
    createdAt: '05 September 2026',
  },
  {
    id: 'rev-06-2',
    productId: 'acr-set-06',
    userName: 'Amitava Banerjee',
    userCity: 'Kolkata, WB',
    rating: 5,
    title: 'Cool, crisp percale weave ideal for hot seasons',
    comment: 'The 300 thread count percale has that distinct crisp snap. Very breathable and easy to maintain.',
    verifiedPurchase: true,
    createdAt: '29 August 2026',
  },
  {
    id: 'rev-06-3',
    productId: 'acr-set-06',
    userName: 'Shreya Mukherjee',
    userCity: 'Siliguri, WB',
    rating: 5,
    title: 'Central medallion is mathematically symmetrical and crisp',
    comment: 'Masterpiece level precision in the loom pattern. The pillow covers match the medallion border symmetry seamlessly.',
    verifiedPurchase: true,
    createdAt: '19 August 2026',
  },

  // Edition 07 — Cobalt Lattice Framing
  {
    id: 'rev-07-1',
    productId: 'acr-set-07',
    userName: 'Meera Krishnan',
    userCity: 'Hyderabad, TS',
    rating: 5,
    title: 'Crisp, structured borders with zero pilling',
    comment: 'After three washes, the indigo color has not bled a single drop and the cotton has only become softer. The framing border gives our room a tailored European hotel vibe.',
    verifiedPurchase: true,
    createdAt: '08 September 2026',
  },
  {
    id: 'rev-07-2',
    productId: 'acr-set-07',
    userName: 'Vijay Anand',
    userCity: 'Tirupur, TN',
    rating: 5,
    title: 'The bordered lattice looks like an antique European manor set',
    comment: 'Coming from a textile town myself, I can immediately recognize dense, high-grade yarn. Outstanding weave tension and stitch quality.',
    verifiedPurchase: true,
    createdAt: '01 September 2026',
  },
  {
    id: 'rev-07-3',
    productId: 'acr-set-07',
    userName: 'Divya Chettiar',
    userCity: 'Karaikudi, TN',
    rating: 5,
    title: 'Dense weave with zero color bleed',
    comment: 'The cobalt blue is regal and the geometric border frames the bed frame beautifully. Highly recommended.',
    verifiedPurchase: true,
    createdAt: '21 August 2026',
  },

  // Edition 08 — Tonal Botanical Sateen
  {
    id: 'rev-08-1',
    productId: 'acr-set-08',
    userName: 'Abhishek Roy',
    userCity: 'New Delhi, DL',
    rating: 5,
    title: 'Classical botanical relief weave',
    comment: 'The tonal neutral palette matches our teak wood headboard gorgeously. Heavier weight than standard sheets.',
    verifiedPurchase: true,
    createdAt: '13 September 2026',
  },
  {
    id: 'rev-08-2',
    productId: 'acr-set-08',
    userName: 'Rajeshwari Iyer',
    userCity: 'Thanjavur, TN',
    rating: 5,
    title: 'Earth-toned elegance that compliments natural wood',
    comment: 'The neutral ecru and taupe hues are understated and refined. The fabric texture is soothing and soft.',
    verifiedPurchase: true,
    createdAt: '04 September 2026',
  },
  {
    id: 'rev-08-3',
    productId: 'acr-set-08',
    userName: 'Anirudh Saxena',
    userCity: 'Gurugram, HR',
    rating: 5,
    title: 'The 350 TC combed cotton has a calm, soothing touch',
    comment: 'Outstanding quality. You can tell real attention went into the spinning and weaving process.',
    verifiedPurchase: true,
    createdAt: '23 August 2026',
  },

  // Edition 09 — Baroque Damask
  {
    id: 'rev-09-1',
    productId: 'acr-set-09',
    userName: 'Lakshmi Narayanan',
    userCity: 'Salem, TN',
    rating: 5,
    title: 'Heavyweight 420 TC weave — stays completely wrinkle-free',
    comment: 'The 380 GSM fabric stays locked in place. The regency scrollwork is woven with razor precision.',
    verifiedPurchase: true,
    createdAt: '07 September 2026',
  },
  {
    id: 'rev-09-2',
    productId: 'acr-set-09',
    userName: 'Meenakshi Sundaram',
    userCity: 'Tirunelveli, TN',
    rating: 5,
    title: 'Heavyweight architectural drape that stays taut all day',
    comment: 'Gives the bed a tailored, structured appearance without needing ironing. Pure long-staple cotton luxury.',
    verifiedPurchase: true,
    createdAt: '30 August 2026',
  },
  {
    id: 'rev-09-3',
    productId: 'acr-set-09',
    userName: 'Harish Pillai',
    userCity: 'Ernakulam, KL',
    rating: 5,
    title: 'Regal scrollwork with deep tactile relief in the weave',
    comment: 'The jacquard patterns have a tactile 3D relief that catches ambient room light beautifully.',
    verifiedPurchase: true,
    createdAt: '15 August 2026',
  },

  // Edition 10 — Gold Medallion Damask
  {
    id: 'rev-10-1',
    productId: 'acr-set-10',
    userName: 'Pranav Joshi',
    userCity: 'Pune, MH',
    rating: 5,
    title: 'Silken finish with crown jewel motif',
    comment: 'The damask weaving creates a two-tone shimmer depending on the light angle. Exceptional luxury finish.',
    verifiedPurchase: true,
    createdAt: '09 September 2026',
  },
  {
    id: 'rev-10-2',
    productId: 'acr-set-10',
    userName: 'Arvind Chawla',
    userCity: 'New Delhi, DL',
    rating: 5,
    title: 'The shimmer under evening lighting is astonishingly luxurious',
    comment: 'Very majestic center medallion. Guests have complimented it every single time they stepped into our room.',
    verifiedPurchase: true,
    createdAt: '02 September 2026',
  },
  {
    id: 'rev-10-3',
    productId: 'acr-set-10',
    userName: 'Nandita Sen',
    userCity: 'Bhubaneswar, OD',
    rating: 5,
    title: 'High thread count luxury without synthetic polyester',
    comment: 'Pure natural cotton that feels cool and luxurious against the skin. Will definitely be a returning patron.',
    verifiedPurchase: true,
    createdAt: '17 August 2026',
  },

  // Curated Boxes & Cushions
  {
    id: 'rev-box-1',
    productId: 'box-royal-neutral',
    userName: 'Priya & Vikram Shah',
    userCity: 'Mumbai, MH',
    rating: 5,
    title: 'Ordered this for our housewarming — breathtaking packaging',
    comment: 'The keepsake gold-embossed box and wax-seal presentation made opening it feel like an event. The velvet lumbar pillow alongside the bedspread makes the whole bed look like an architectural magazine shoot.',
    verifiedPurchase: true,
    createdAt: '15 September 2026',
  },
  {
    id: 'rev-box-2',
    productId: 'box-bold-vibrant',
    userName: 'Siddharth Nair',
    userCity: 'Bangalore, KA',
    rating: 5,
    title: 'Spectacular gift for my parents’ anniversary',
    comment: 'They were thrilled by the Erode weave quality and the bespoke packaging. The extra decorative cushion is plush and firm.',
    verifiedPurchase: true,
    createdAt: '12 September 2026',
  },
  {
    id: 'rev-cushion-1',
    productId: 'cushion-velvet-lumbar',
    userName: 'Rohan Deshmukh',
    userCity: 'Pune, MH',
    rating: 5,
    title: 'Dense, rich velvet and perfect lumbar support',
    comment: 'Placed this on our reading armchair. The fabric has an understated glow without being flashy. Excellent micro-cluster insert support.',
    verifiedPurchase: true,
    createdAt: '19 August 2026',
  },
];
