import { Review } from './types';

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-01',
    productId: 'acr-set-01',
    userName: 'Kavitha Ramaswamy',
    userCity: 'Chennai, TN',
    rating: 5,
    title: 'Pure boutique hotel luxury for our master suite',
    comment: 'The navy and gold damask pattern is even more stunning in person than on screen. The fabric has an authentic weight to it that stays perfectly in place on our king bed. Woven craftsmanship at its absolute finest.',
    verifiedPurchase: true,
    createdAt: '12 September 2026',
  },
  {
    id: 'rev-02',
    productId: 'acr-set-01',
    userName: 'Arjun Menon',
    userCity: 'Bangalore, KA',
    rating: 5,
    title: 'The combed cotton breathability is remarkable',
    comment: 'Unlike polyester blends that get stuffy, this combed cotton breathes wonderfully through warm Bangalore nights. The two matching pillow covers complete the aesthetic effortlessly.',
    verifiedPurchase: true,
    createdAt: '04 September 2026',
  },
  {
    id: 'rev-03',
    productId: 'acr-set-01',
    userName: 'Sangeetha Natarajan',
    userCity: 'Coimbatore, TN',
    rating: 5,
    title: 'Proud of our Erode textile heritage',
    comment: 'Knowing this is woven right here in the Textile Valley of Erode makes it even more special. The hemstitch borders and jacquard relief are pristine. Will be ordering another set for the guest bedroom.',
    verifiedPurchase: true,
    createdAt: '28 August 2026',
  },
  {
    id: 'rev-04',
    productId: 'box-royal-neutral',
    userName: 'Priya & Vikram Shah',
    userCity: 'Mumbai, MH',
    rating: 5,
    title: 'Ordered this for our housewarming — breathtaking packaging',
    comment: 'The keepsake gold-embossed box and wax-seal presentation made opening it feel like an event. The velvet lumbar pillow alongside the bedspread makes the whole bed look like an architectural magazine shoot.',
    verifiedPurchase: true,
    createdAt: '15 September 2026',
  },
  {
    id: 'rev-05',
    productId: 'acr-set-07',
    userName: 'Meera Krishnan',
    userCity: 'Hyderabad, TS',
    rating: 5,
    title: 'Crisp, structured borders with zero pilling',
    comment: 'After three washes, the indigo color has not bled a single drop and the cotton has only become softer. The framing border gives our room a tailored European hotel vibe.',
    verifiedPurchase: true,
    createdAt: '08 September 2026',
  },
  {
    id: 'rev-06',
    productId: 'cushion-velvet-lumbar',
    userName: 'Rohan Deshmukh',
    userCity: 'Pune, MH',
    rating: 5,
    title: 'Dense, rich velvet and perfect lumbar support',
    comment: 'Placed this on our reading armchair. The fabric has an understated glow without being flashy. Excellent micro-cluster insert support.',
    verifiedPurchase: true,
    createdAt: '19 August 2026',
  },
];
